### ISSUE TITLE
Incluir extractos de las reuniones

### ISSUE THREAD

**Issue by David-informatica** [JesusDtC/ISO2-2023-B01#14]
Se deben sacar extractos de las reuniones a partir del word compartido donde se recopila toda la información de las reuniones.

**Comment by JesusDtC** [comment]
👀

**Comment by David-informatica** [comment]
Quedan añadidos todos los extractos de las reuniones celebradas hasta la fecha, obtenidos del word compartido donde se anotaba todo lo relaccionado con las reuniones.
