### ISSUE TITLE
Beta release - 21 de Diciembre

### ISSUE THREAD

**Issue by David-informatica** [JesusDtC/ISO2-2023-B01#38]
Cualquier discordancia con la planificación o el calendario pueden verse resueltas en la [ultima reunion](https://github.com/JesusDtC/ISO2-2023-B01/wiki/Reuniones-%F0%9F%93%8A#novena-reuni%C3%B3n-8).

**Comment by JesusDtC** [comment]
✅ ✅ ✅ ✅
