### ISSUE TITLE
Incluir tabla de flujo de trabajo (workflow)

### ISSUE THREAD

**Issue by David-informatica** [JesusDtC/ISO2-2023-B01#40]
Añadir tabla workflow en el apartado de [autoevaluación](https://github.com/JesusDtC/ISO2-2023-B01/wiki/Autoevaluaci%C3%B3n-%F0%9F%A5%87) con las columnas: iteración, componente, versión, clase(s), versión de clase, RF, dependencias.

**Comment by Iam-Jorge** [comment]
[Tabla añadida](https://github.com/JesusDtC/ISO2-2023-B01/wiki/Autoevaluación-🥇)
